%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#ff3f3fff',
      'primaryBorderColor': '#bf0000ff',
      'primaryTextColor': '#fff',
      'tertiaryColor': '#ff3f3f0f',
      'tertiaryBorderColor': '#bf0000ff',
      'tertiaryTextColor': '#bf0000ff',
      'lineColor': '#bf0000ff',
      'fontSize': '16px',
      'fontFamily': 'Lucida Grande'
    }
  }
}%%

graph TD
  subgraph PoppyOS[Poppy OS]
    subgraph PSC[Poppy Software Compilation]
      direction RL

      subgraph PSC_Progs[Программы, приложения]
        direction TB

        subgraph PSC_User[Вручную запускаемые пользователем]
          direction TB

          Code
          SysPref[System Preferences]
          ActMon[Activity Monitor]
        end

        subgraph PSC_Automatic[Автоматически поддерживаемые launchd]
          direction TB

          subgraph launchd_daemons[Launch Daemons]
            WindowServer
            LoginWindow
          end

          subgraph launchd_agents[Launch Agents]
            Enviro
            Dock
          end
        end

        PSC_User --> PSC_Automatic
      end

      subgraph PSC_Libs[Библиотеки, фреймворки]
        direction TB

        CFFramework[CoreFoundation Framework]
        CTFramework[CoreTypes Framework]
        CGFramework[CoreGraphics Framework]
        LFFramework[Leaf Framework]

        LFFramework --> CGFramework --> CFFramework
        CTFramework --> CFFramework --> libSystem
      end

      PSC_Progs --> PSC_Libs
    end

    subgraph K1["Ядро уровня 1 (Opium)"]
      direction RL

      subgraph KEM[Kernel Execution Marshall]
        direction TB

        KEM_Root[Root]
        KEM_Wasm[WebAssembly]
        KEM_ELF[ELF]
      end

      subgraph IOKit[Input/Output Kit]
        IOKit_Services[Services]
      end

      subgraph BSD[Berkeley Software Distribution]
        direction TB

        BSD_Scheduling[Scheduling]
        BSD_IPC[Inter-Process Communication]
        BSD_IO[Input/Output]
        BSD_TTY[Terminal]
        BSD_EventHandler[Event Handler]

        subgraph BSD_VFS[Virtual File System]
          direction TB

          DevFS
          TmpFS
          ProcFS
        end

        BSD_IPC --> BSD_Scheduling
        BSD_VFS --> BSD_IO
        BSD_TTY --> BSD_IO --> BSD_EventHandler
      end

      subgraph Mach
        direction TB

        Mach_IPC[Inter-Process Communication] -->  Mach_Scheduling[Scheduling]
      end

      subgraph KPL[Kernel Portability Layer]
        direction TB

        KPL_Unknown[Unknown]
        KPL_FreeBSD[FreeBSD]
        KPL_Linux[Linux]
      end

      subgraph KEL[Kernel Extension Loader]
        direction TB

        KEL_Generic[Общие расширения]
        KEL_VFS[Расширения VFS]
        KEL_IOKit[Расширения IOKit]
      end

      KEM --> IOKit --> BSD --> Mach --> KPL
    end

    PSC --> K1 --> K0["Ядро уровня 0"]
  end

  PoppyOS --> Hardware[Аппаратное обеспечение]